version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gin-backend:latest
    container_name: gin-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
