version: "3.8"
services:
  app:
    image: golang:1.22
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "go run main.go"
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
//docker-compose.override.yml